//
//  BetToCards.swift
//  Blef
//
//  Created by Adrian Golian on 03.05.20.
//  Copyright © 2020 Blef Team.
//

import Foundation
import UIKit

let BetToCards = makeBetToCards()

func makeBetToCards() -> [Action: [UIImage]] {
    return [
        .highCard9: [#imageLiteral(resourceName: "card-nine")],
        .highCard10: [#imageLiteral(resourceName: "card-ten")],
        .highCardJ: [#imageLiteral(resourceName: "card-jack")],
        .highCardQ: [#imageLiteral(resourceName: "card-queen")],
        .highCardK: [#imageLiteral(resourceName: "card-king")],
        .highCardA: [#imageLiteral(resourceName: "card-ace")],
        .pairOf9s: [#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine")],
        .pairOf10s: [#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten")],
        .pairOfJs: [#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack")],
        .pairOfQs: [#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen")],
        .pairOfKs: [#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king")],
        .pairOfAs: [#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace")],
        .twoPairs10sAnd9s: [#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine")],
        .twoPairsJsAnd9s: [#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine")],
        .twoPairsJsAnd10s: [#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten")],
        .twoPairsQsAnd9s: [#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine")],
        .twoPairsQsAnd10s: [#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten")],
        .twoPairsQsAndJs: [#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack")],
        .twoPairsKsAnd9s: [#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine")],
        .twoPairsKsAnd10s: [#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten")],
        .twoPairsKsAndJs: [#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack"),],
        .twoPairsKsAndQs: [#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen")],
        .twoPairsAsAnd9s: [#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine")],
        .twoPairsAsAnd10s: [#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten")],
        .twoPairsAsAndJs: [#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack"),],
        .twoPairsAsAndQs: [#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen")],
        .twoPairsAsAndKs: [#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king")],
        .smallStraight: [#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-king")],
        .bigStraight: [#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-ace")],
        .greatStraight: [#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-ace")],
        .three9s: [#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine")],
        .three10s: [#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten")],
        .threeJs: [#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack")],
        .threeQs: [#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen")],
        .threeKs: [#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king")],
        .threeAs: [#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace")],
        .fullHouse9sOver10s: [#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten")],
        .fullHouse9sOverJs: [#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack")],
        .fullHouse9sOverQs: [#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen")],
        .fullHouse9sOverKs: [#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king")],
        .fullHouse9sOverAs: [#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace")],
        .fullHouse10sOver9s: [#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine")],
        .fullHouse10sOverJs: [#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack")],
        .fullHouse10sOverQs: [#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen")],
        .fullHouse10sOverKs: [#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king")],
        .fullHouse10sOverAs: [#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace")],
        .fullHouseJsOver9s: [#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine")],
        .fullHouseJsOver10s: [#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten")],
        .fullHouseJsOverQs: [#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen")],
        .fullHouseJsOverKs: [#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king")],
        .fullHouseJsOverAs: [#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace")],
        .fullHouseQsOver9s: [#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine")],
        .fullHouseQsOver10s: [#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten")],
        .fullHouseQsOverJs: [#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack")],
        .fullHouseQsOverKs: [#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king")],
        .fullHouseQsOverAs: [#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace")],
        .fullHouseKsOver9s: [#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine")],
        .fullHouseKsOver10s: [#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten")],
        .fullHouseKsOverJs: [#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack")],
        .fullHouseKsOverQs: [#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen")],
        .fullHouseKsOverAs: [#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace")],
        .fullHouseAsOver9s: [#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine")],
        .fullHouseAsOver10s: [#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten")],
        .fullHouseAsOverJs: [#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack")],
        .fullHouseAsOverQs: [#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen")],
        .fullHouseAsOverKs: [#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king")],
        .flushClubs: [#imageLiteral(resourceName: "card-clubs"),#imageLiteral(resourceName: "card-clubs"),#imageLiteral(resourceName: "card-clubs"),#imageLiteral(resourceName: "card-clubs"),#imageLiteral(resourceName: "card-clubs")],
        .flushDiamonds: [#imageLiteral(resourceName: "card-diamonds"),#imageLiteral(resourceName: "card-diamonds"),#imageLiteral(resourceName: "card-diamonds"),#imageLiteral(resourceName: "card-diamonds"),#imageLiteral(resourceName: "card-diamonds")],
        .flushHearts: [#imageLiteral(resourceName: "card-hearts"),#imageLiteral(resourceName: "card-hearts"),#imageLiteral(resourceName: "card-hearts"),#imageLiteral(resourceName: "card-hearts"),#imageLiteral(resourceName: "card-hearts")],
        .flushSpades: [#imageLiteral(resourceName: "card-spades"),#imageLiteral(resourceName: "card-spades"),#imageLiteral(resourceName: "card-spades"),#imageLiteral(resourceName: "card-spades"),#imageLiteral(resourceName: "card-spades")],
        .four9s: [#imageLiteral(resourceName: "card-nine-spades"),#imageLiteral(resourceName: "card-nine-hearts"),#imageLiteral(resourceName: "card-nine-diamonds"),#imageLiteral(resourceName: "card-nine-clubs")],
        .four10s: [#imageLiteral(resourceName: "card-ten-spades"),#imageLiteral(resourceName: "card-ten-hearts"),#imageLiteral(resourceName: "card-ten-diamonds"),#imageLiteral(resourceName: "card-ten-clubs")],
        .fourJs: [#imageLiteral(resourceName: "card-jack-spades"),#imageLiteral(resourceName: "card-jack-hearts"),#imageLiteral(resourceName: "card-jack-diamonds"),#imageLiteral(resourceName: "card-jack-clubs")],
        .fourQs: [#imageLiteral(resourceName: "card-queen-spades"),#imageLiteral(resourceName: "card-queen-hearts"),#imageLiteral(resourceName: "card-queen-diamonds"),#imageLiteral(resourceName: "card-queen-clubs")],
        .fourKs: [#imageLiteral(resourceName: "card-king-spades"),#imageLiteral(resourceName: "card-king-hearts"),#imageLiteral(resourceName: "card-king-diamonds"),#imageLiteral(resourceName: "card-king-clubs")],
        .fourAs: [#imageLiteral(resourceName: "card-ace-spades"),#imageLiteral(resourceName: "card-ace-hearts"),#imageLiteral(resourceName: "card-ace-diamonds"),#imageLiteral(resourceName: "card-ace-clubs")],
        .smallStraightFlushClubs: [#imageLiteral(resourceName: "card-nine-clubs"),#imageLiteral(resourceName: "card-ten-clubs"),#imageLiteral(resourceName: "card-jack-clubs"),#imageLiteral(resourceName: "card-queen-clubs"),#imageLiteral(resourceName: "card-king-clubs")],
        .smallStraightFlushDiamonds: [#imageLiteral(resourceName: "card-nine-diamonds"),#imageLiteral(resourceName: "card-ten-diamonds"),#imageLiteral(resourceName: "card-jack-diamonds"),#imageLiteral(resourceName: "card-queen-diamonds"),#imageLiteral(resourceName: "card-king-diamonds")],
        .smallStraightFlushHearts: [#imageLiteral(resourceName: "card-nine-hearts"),#imageLiteral(resourceName: "card-ten-hearts"),#imageLiteral(resourceName: "card-jack-hearts"),#imageLiteral(resourceName: "card-queen-hearts"),#imageLiteral(resourceName: "card-king-hearts")],
        .smallStraightFlushSpades: [#imageLiteral(resourceName: "card-nine-spades"),#imageLiteral(resourceName: "card-ten-spades"),#imageLiteral(resourceName: "card-jack-spades"),#imageLiteral(resourceName: "card-queen-spades"),#imageLiteral(resourceName: "card-king-spades")],
        .bigStraightFlushClubs: [#imageLiteral(resourceName: "card-ten-clubs"),#imageLiteral(resourceName: "card-jack-clubs"),#imageLiteral(resourceName: "card-queen-clubs"),#imageLiteral(resourceName: "card-king-clubs"),#imageLiteral(resourceName: "card-ace-clubs")],
        .bigStraightFlushDiamonds: [#imageLiteral(resourceName: "card-ten-diamonds"),#imageLiteral(resourceName: "card-jack-diamonds"),#imageLiteral(resourceName: "card-queen-diamonds"),#imageLiteral(resourceName: "card-king-diamonds"),#imageLiteral(resourceName: "card-ace-diamonds")],
        .bigStraightFlushHearts: [#imageLiteral(resourceName: "card-ten-hearts"),#imageLiteral(resourceName: "card-jack-hearts"),#imageLiteral(resourceName: "card-queen-hearts"),#imageLiteral(resourceName: "card-king-hearts"),#imageLiteral(resourceName: "card-ace-hearts")],
        .bigStraightFlushSpades: [#imageLiteral(resourceName: "card-ten-spades"),#imageLiteral(resourceName: "card-jack-spades"),#imageLiteral(resourceName: "card-queen-spades"),#imageLiteral(resourceName: "card-king-spades"),#imageLiteral(resourceName: "card-ace-spades")],
        .greatStraightFlushClubs: [#imageLiteral(resourceName: "card-nine-clubs"),#imageLiteral(resourceName: "card-ten-clubs"),#imageLiteral(resourceName: "card-jack-clubs"),#imageLiteral(resourceName: "card-queen-clubs"),#imageLiteral(resourceName: "card-king-clubs"),#imageLiteral(resourceName: "card-ace-clubs")],
        .greatStraightFlushDiamonds: [#imageLiteral(resourceName: "card-nine-diamonds"),#imageLiteral(resourceName: "card-ten-diamonds"),#imageLiteral(resourceName: "card-jack-diamonds"),#imageLiteral(resourceName: "card-queen-diamonds"),#imageLiteral(resourceName: "card-king-diamonds"),#imageLiteral(resourceName: "card-ace-diamonds")],
        .greatStraightFlushHearts: [#imageLiteral(resourceName: "card-nine-hearts"),#imageLiteral(resourceName: "card-ten-hearts"),#imageLiteral(resourceName: "card-jack-hearts"),#imageLiteral(resourceName: "card-queen-hearts"),#imageLiteral(resourceName: "card-king-hearts"),#imageLiteral(resourceName: "card-ace-hearts")],
        .greatStraightFlushSpades: [#imageLiteral(resourceName: "card-nine-spades"),#imageLiteral(resourceName: "card-ten-spades"),#imageLiteral(resourceName: "card-jack-spades"),#imageLiteral(resourceName: "card-queen-spades"),#imageLiteral(resourceName: "card-king-spades"),#imageLiteral(resourceName: "card-ace-spades")],
    ]
}
