//
//  BetToCards.swift
//  Blef
//
//  Created by Adrian Golian on 03.05.20.
//  Copyright © 2020 Blef Team.
//

import Foundation
import UIKit

let BetToCards = makeBetToCards()

func makeBetToCards() -> [Action: [UIImage]] {
    return [
        .highCard9: [#imageLiteral(resourceName: "card-nine")],
        .highCard10: [#imageLiteral(resourceName: "card-ten")],
        .highCardJ: [#imageLiteral(resourceName: "card-jack")],
        .highCardQ: [#imageLiteral(resourceName: "card-queen")],
        .highCardK: [#imageLiteral(resourceName: "card-king")],
        .highCardA: [#imageLiteral(resourceName: "card-ace")],
        .pairOf9s: [#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine")],
        .pairOf10s: [#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten")],
        .pairOfJs: [#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack")],
        .pairOfQs: [#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen")],
        .pairOfKs: [#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king")],
        .pairOfAs: [#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace")],
        .twoPairs10sAnd9s: [#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten")],
        .twoPairsJsAnd9s: [#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine")],
        .twoPairsJsAnd10s: [#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten")],
        .twoPairsQsAnd9s: [#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine")],
        .twoPairsQsAnd10s: [#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten")],
        .twoPairsQsAndJs: [#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack")],
        .twoPairsKsAnd9s: [#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine")],
        .twoPairsKsAnd10s: [#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten")],
        .twoPairsKsAndJs: [#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack"),],
        .twoPairsKsAndQs: [#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen")],
        .twoPairsAsAnd9s: [#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine")],
        .twoPairsAsAnd10s: [#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten")],
        .twoPairsAsAndJs: [#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack"),],
        .twoPairsAsAndQs: [#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen")],
        .twoPairsAsAndKs: [#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king")],
        .smallStraight: [#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-king")],
        .bigStraight: [#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-ace")],
        .greatStraight: [#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-ace")],
        .three9s: [#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine")],
        .three10s: [#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten")],
        .threeJs: [#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack")],
        .threeQs: [#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen")],
        .threeKs: [#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king")],
        .threeAs: [#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace")],
        .fullHouse9sOn10s: [#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten")],
        .fullHouse9sOnJs: [#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack")],
        .fullHouse9sOnQs: [#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen")],
        .fullHouse9sOnKs: [#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king")],
        .fullHouse9sOnAs: [#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace")],
        .fullHouse10sOn9s: [#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine")],
        .fullHouse10sOnJs: [#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack")],
        .fullHouse10sOnQs: [#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen")],
        .fullHouse10sOnKs: [#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king")],
        .fullHouse10sOnAs: [#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace")],
        .fullHouseJsOn9s: [#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine")],
        .fullHouseJsOn10s: [#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten")],
        .fullHouseJsOnQs: [#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen")],
        .fullHouseJsOnKs: [#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king")],
        .fullHouseJsOnAs: [#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace")],
        .fullHouseQsOn9s: [#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine")],
        .fullHouseQsOn10s: [#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten")],
        .fullHouseQsOnJs: [#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack")],
        .fullHouseQsOnKs: [#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king")],
        .fullHouseQsOnAs: [#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace")],
        .fullHouseKsOn9s: [#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine")],
        .fullHouseKsOn10s: [#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten")],
        .fullHouseKsOnJs: [#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack")],
        .fullHouseKsOnQs: [#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen")],
        .fullHouseKsOnAs: [#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace")],
        .fullHouseAsOn9s: [#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-nine"),#imageLiteral(resourceName: "card-nine")],
        .fullHouseAsOn10s: [#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ten"),#imageLiteral(resourceName: "card-ten")],
        .fullHouseAsOnJs: [#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-jack"),#imageLiteral(resourceName: "card-jack")],
        .fullHouseAsOnQs: [#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-queen"),#imageLiteral(resourceName: "card-queen")],
        .fullHouseAsOnKs: [#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-ace"),#imageLiteral(resourceName: "card-king"),#imageLiteral(resourceName: "card-king")],
        .colourClubs: [#imageLiteral(resourceName: "card-hearts"),#imageLiteral(resourceName: "card-hearts"),#imageLiteral(resourceName: "card-hearts"),#imageLiteral(resourceName: "card-hearts"),#imageLiteral(resourceName: "card-hearts")],
        .colourDiamonds: [#imageLiteral(resourceName: "card-hearts"),#imageLiteral(resourceName: "card-hearts"),#imageLiteral(resourceName: "card-hearts"),#imageLiteral(resourceName: "card-hearts"),#imageLiteral(resourceName: "card-hearts")],
        .colourHearts: [#imageLiteral(resourceName: "card-hearts"),#imageLiteral(resourceName: "card-hearts"),#imageLiteral(resourceName: "card-hearts"),#imageLiteral(resourceName: "card-hearts"),#imageLiteral(resourceName: "card-hearts")],
        .colourSpades: [#imageLiteral(resourceName: "card-spades"),#imageLiteral(resourceName: "card-spades"),#imageLiteral(resourceName: "card-spades"),#imageLiteral(resourceName: "card-spades"),#imageLiteral(resourceName: "card-spades")],
        .four9s: [#imageLiteral(resourceName: "card-nine-spades"),#imageLiteral(resourceName: "card-nine-hearts"),#imageLiteral(resourceName: "card-nine-diamonds"),#imageLiteral(resourceName: "card-nine-clubs")],
        .four10s: [#imageLiteral(resourceName: "card-ten-spades"),#imageLiteral(resourceName: "card-ten-hearts"),#imageLiteral(resourceName: "card-ten-diamonds"),#imageLiteral(resourceName: "card-ten-clubs")],
        .fourJs: [#imageLiteral(resourceName: "card-jack-spades"),#imageLiteral(resourceName: "card-jack-hearts"),#imageLiteral(resourceName: "card-jack-diamonds"),#imageLiteral(resourceName: "card-jack-clubs")],
        .fourQs: [#imageLiteral(resourceName: "card-queen-spades"),#imageLiteral(resourceName: "card-queen-hearts"),#imageLiteral(resourceName: "card-queen-diamonds"),#imageLiteral(resourceName: "card-queen-clubs")],
        .fourKs: [#imageLiteral(resourceName: "card-king-spades"),#imageLiteral(resourceName: "card-king-hearts"),#imageLiteral(resourceName: "card-king-diamonds"),#imageLiteral(resourceName: "card-king-clubs")],
        .fourAs: [#imageLiteral(resourceName: "card-ace-spades"),#imageLiteral(resourceName: "card-ace-hearts"),#imageLiteral(resourceName: "card-ace-diamonds"),#imageLiteral(resourceName: "card-ace-clubs")],
        .smallFlushClubs: [#imageLiteral(resourceName: "card-nine-clubs"),#imageLiteral(resourceName: "card-ten-clubs"),#imageLiteral(resourceName: "card-jack-clubs"),#imageLiteral(resourceName: "card-queen-clubs"),#imageLiteral(resourceName: "card-king-clubs")],
        .smallFlushDiamonds: [#imageLiteral(resourceName: "card-nine-diamonds"),#imageLiteral(resourceName: "card-ten-diamonds"),#imageLiteral(resourceName: "card-jack-diamonds"),#imageLiteral(resourceName: "card-queen-diamonds"),#imageLiteral(resourceName: "card-king-diamonds")],
        .smallFlushHearts: [#imageLiteral(resourceName: "card-nine-hearts"),#imageLiteral(resourceName: "card-ten-hearts"),#imageLiteral(resourceName: "card-jack-hearts"),#imageLiteral(resourceName: "card-queen-hearts"),#imageLiteral(resourceName: "card-king-hearts")],
        .smallFlushSpades: [#imageLiteral(resourceName: "card-nine-spades"),#imageLiteral(resourceName: "card-ten-spades"),#imageLiteral(resourceName: "card-jack-spades"),#imageLiteral(resourceName: "card-queen-spades"),#imageLiteral(resourceName: "card-king-spades")],
        .bigFlushClubs: [#imageLiteral(resourceName: "card-ten-clubs"),#imageLiteral(resourceName: "card-jack-clubs"),#imageLiteral(resourceName: "card-queen-clubs"),#imageLiteral(resourceName: "card-king-clubs"),#imageLiteral(resourceName: "card-ace-clubs")],
        .bigFlushDiamonds: [#imageLiteral(resourceName: "card-ten-diamonds"),#imageLiteral(resourceName: "card-jack-diamonds"),#imageLiteral(resourceName: "card-queen-diamonds"),#imageLiteral(resourceName: "card-king-diamonds"),#imageLiteral(resourceName: "card-ace-diamonds")],
        .bigFlushHearts: [#imageLiteral(resourceName: "card-ten-hearts"),#imageLiteral(resourceName: "card-jack-hearts"),#imageLiteral(resourceName: "card-queen-hearts"),#imageLiteral(resourceName: "card-king-hearts"),#imageLiteral(resourceName: "card-ace-hearts")],
        .bigFlushSpades: [#imageLiteral(resourceName: "card-ten-spades"),#imageLiteral(resourceName: "card-jack-spades"),#imageLiteral(resourceName: "card-queen-spades"),#imageLiteral(resourceName: "card-king-spades"),#imageLiteral(resourceName: "card-ace-spades")],
        .greatFlushClubs: [#imageLiteral(resourceName: "card-nine-clubs"),#imageLiteral(resourceName: "card-ten-clubs"),#imageLiteral(resourceName: "card-jack-clubs"),#imageLiteral(resourceName: "card-queen-clubs"),#imageLiteral(resourceName: "card-king-clubs"),#imageLiteral(resourceName: "card-ace-clubs")],
        .greatFlushDiamonds: [#imageLiteral(resourceName: "card-nine-diamonds"),#imageLiteral(resourceName: "card-ten-diamonds"),#imageLiteral(resourceName: "card-jack-diamonds"),#imageLiteral(resourceName: "card-queen-diamonds"),#imageLiteral(resourceName: "card-king-diamonds"),#imageLiteral(resourceName: "card-ace-diamonds")],
        .greatFlushHearts: [#imageLiteral(resourceName: "card-nine-hearts"),#imageLiteral(resourceName: "card-ten-hearts"),#imageLiteral(resourceName: "card-jack-hearts"),#imageLiteral(resourceName: "card-queen-hearts"),#imageLiteral(resourceName: "card-king-hearts"),#imageLiteral(resourceName: "card-ace-hearts")],
        .greatFlushSpades: [#imageLiteral(resourceName: "card-nine-spades"),#imageLiteral(resourceName: "card-ten-spades"),#imageLiteral(resourceName: "card-jack-spades"),#imageLiteral(resourceName: "card-queen-spades"),#imageLiteral(resourceName: "card-king-spades"),#imageLiteral(resourceName: "card-ace-spades")],
    ]
}
